# Generated by Django 5.1.6 on 2025-03-05 12:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
        ('products', '0005_review_has_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='product',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='products.product'),
        ),
    ]
