# Generated by Django 5.1.6 on 2025-03-08 19:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_message_product'),
        ('products', '0005_review_has_paid'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatroom',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='products.product'),
        ),
    ]
