"""
Django settings for MkulimaSystem project.

Generated by 'django-admin startproject' using Django 5.1.4.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/
"""

from pathlib import Path
import os
from dotenv import load_dotenv

load_dotenv()

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = os.getenv('SECRET_KEY')

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'accounts',
    'products',
    'chat',
    'payments',
    'subscriptions',
    'channels',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'MkulimaSystem.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')],  # Ensure this line is present
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'MkulimaSystem.wsgi.application'


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}
# DATABASES = {
#     'default': {
#         'ENGINE': os.getenv('DB_ENGINE'),
#         'NAME': os.getenv('DB_NAME'),
#         'USER': os.getenv('DB_USER'),
#         'PASSWORD': os.getenv('DB_PASSWORD'),
#         'HOST': os.getenv('DB_HOST'),
#         'PORT': os.getenv('DB_PORT'),}
# }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = '/static/'
STATICFILES_DIRS = [os.path.join(BASE_DIR, 'static')]
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')

MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

# Redirect to profile after login
LOGIN_REDIRECT_URL = 'accounts:profile'
LOGOUT_REDIRECT_URL = 'accounts:login'
AUTH_USER_MODEL = 'accounts.User'

# AzamPay settings
AZAMPAY_BASE_URL=os.getenv('AZAMPAY_BASE_URL')
AZAMPAY_CLIENT_ID=os.getenv('AZAMPAY_CLIENT_ID')
AZAMPAY_CLIENT_SECRET=os.getenv('AZAMPAY_CLIENT_SECRET')

# Channels settings
ASGI_APPLICATION = 'MkulimaSystem.asgi.application'

# Redis settings
REDIS_HOST = os.getenv('REDIS_HOST')
REDIS_PORT = os.getenv('REDIS_PORT')
REDIS_DB = os.getenv('REDIS_DB')
REDIS_URL = f'redis://{REDIS_HOST}:{REDIS_PORT}/{REDIS_DB}'
CHANNEL_LAYERS = {
    'default': {
        'BACKEND': 'channels_redis.core.RedisChannelLayer',
        'CONFIG': {
            'hosts': [REDIS_URL],
        },
    },
}

# Email settings
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = os.getenv('EMAIL_HOST')
EMAIL_PORT = os.getenv('EMAIL_PORT')
EMAIL_USE_TLS = True
EMAIL_HOST_USER = os.getenv('EMAIL_HOST_USER')
EMAIL_HOST_PASSWORD = os.getenv('EMAIL_HOST_PASSWORD')
DEFAULT_FROM_EMAIL = os.getenv('DEFAULT_FROM_EMAIL')

# Celery settings
CELERY_BROKER_URL = REDIS_URL
CELERY_RESULT_BACKEND = REDIS_URL
CELERY_ACCEPT_CONTENT = ['json']
CELERY_TASK_SERIALIZER = 'json'
CELERY_RESULT_SERIALIZER = 'json'
CELERY_TIMEZONE = 'UTC'
CELERY_BEAT_SCHEDULE = {
    'send-emails-every-5-minutes': {
        'task': 'subscriptions.tasks.send_emails',
        'schedule': 300.0,
    },
}

# Twilio settings
TWILIO_ACCOUNT_SID = os.getenv('TWILIO_ACCOUNT_SID')
TWILIO_AUTH_TOKEN = os.getenv('TWILIO_AUTH_TOKEN')
TWILIO_PHONE_NUMBER = os.getenv('TWILIO_PHONE_NUMBER')
TWILIO_CALLBACK_URL = os.getenv('TWILIO_CALLBACK_URL')
TWILIO_CALLBACK_METHOD = 'POST'
TWILIO_CALLBACK_EVENT = 'initiated'
TWILIO_CALLBACK_FILTERS = 'initiated,ringing,answered,completed'
TWILIO_CALLBACK_STATUS = 'completed'
TWILIO_CALLBACK_TIMEOUT = 10
TWILIO_CALLBACK_ATTEMPTS = 3
TWILIO_CALLBACK_ATTEMPTS_DELAY = 5

# Sentry settings
SENTRY_DSN = os.getenv('SENTRY_DSN')
SENTRY_ENVIRONMENT = os.getenv('SENTRY_ENVIRONMENT')
SENTRY_RELEASE = os.getenv('SENTRY_RELEASE')
SENTRY_TRACES_SAMPLE_RATE = 1.0
SENTRY_TRANSPORT = 'sentry_sdk.transport.threaded.ThreadedHTTPTransport'
SENTRY_TRACES_INTEGRATION = 'sentry_sdk.integrations.django.DjangoIntegration'
SENTRY_TRACES_SAMPLE_RATE = 1.0
SENTRY_TRACES_COLLECT_LOCAL_VARIABLES = False
SENTRY_TRACES_COLLECT_ARGUMENTS = False
SENTRY_TRACES_COLLECT_PARAMETERS = False
SENTRY_TRACES_COLLECT_PAYLOADS = False
SENTRY_TRACES_COLLECT_QUERY_STRING = False
SENTRY_TRACES_COLLECT_HEADERS = False
SENTRY_TRACES_COLLECT_BODY = False
SENTRY_TRACES_COLLECT_COOKIES = False
SENTRY_TRACES_COLLECT_ENVIRONMENT = False
SENTRY_TRACES_COLLECT_USER = False
SENTRY_TRACES_COLLECT_TAGS = False
SENTRY_TRACES_COLLECT_REQUESTS = False
SENTRY_TRACES_COLLECT_RESPONSES = False
SENTRY_TRACES_COLLECT_SESSIONS = False

# Sentry SDK settings
# import sentry_sdk
# from sentry_sdk.integrations.django import DjangoIntegration
# from sentry_sdk.integrations.redis import RedisIntegration
# from sentry_sdk.integrations.rq import RqIntegration
# from sentry_sdk.integrations.celery import CeleryIntegration
# from sentry_sdk.integrations.logging import LoggingIntegration
# from sentry_sdk.integrations.stdlib import StdlibIntegration
# from sentry_sdk.integrations.excepthook import ExcepthookIntegration
# from sentry_sdk.integrations.atexit import AtexitIntegration
# from sentry_sdk.integrations.modules import ModulesIntegration
# from sentry_sdk.integrations.argv import ArgvIntegration
# from sentry_sdk.integrations.site import SiteIntegration
# from sentry_sdk.integrations.modules import ModulesIntegration

