# Generated by Django 5.1.6 on 2025-03-05 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_review'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='has_paid',
            field=models.BooleanField(default=False),
        ),
    ]
